import * as process from 'process';
import Script from 'next/script';

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport"/>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
      {process.env.NODE_ENV === "production" && (
        <>
          <Script async src="https://www.googletagmanager.com/gtag/js?id=G-BT8Y8XQXP0"/>
          <Script id="google-analytics" strategy='afterInteractive' dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-BT8Y8XQXP0');`
          }}/>
        </>
      )}
    </>
  )
}
